-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.rooms
(
    id serial NOT NULL,
    name text NOT NULL,
    users text[],
    creator_id serial NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username text NOT NULL,
    hash text NOT NULL,
    salt text NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT name UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    id serial NOT NULL,
    content text NOT NULL,
    sended_at timestamp with time zone NOT NULL DEFAULT NOW(),
    sender_id serial NOT NULL,
    room_id serial NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.rooms
    ADD FOREIGN KEY (creator_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.messages
    ADD FOREIGN KEY (room_id)
    REFERENCES public.rooms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.messages
    ADD FOREIGN KEY (sender_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;